#index:
#    path: /
#    controller: App\Controller\DefaultController::index


# rutas de usuario
user:
   path: /user
   controller: App\Controller\UserController::index



# rutas de video
video:
   path: /video
   controller: App\Controller\VideoController::index