#index:
#    path: /
#    controller: App\Controller\DefaultController::index


# rutas de usuario
user:
   path: /user
   controller: App\Controller\UserController::index

register:
   path: /register
   controller: App\Controller\UserController::create
   methods: [POST]

login:
   path: /login
   controller: App\Controller\UserController::login
   methods: [POST]


# rutas de video
video:
   path: /video
   controller: App\Controller\VideoController::index